POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Jack Jakababa",
  "number": "0700001001"
}

###
# Online Request
POST https://full-stack-open-eta.vercel.app/api/persons
Content-Type: application/json

{
  "name": "John Doe",
  "number": "07000000000"
}